### ISSUE TITLE
Version 0.2 Checklist

### ISSUE THREAD

**Issue by markbandstra** [lbl-anp/becquerel#120]
From our discussion today regarding goals for the next minor version.

Tentative date for the new version set at 2018-08-28.

# Major issues/PRs
- [ ] #29 / #78 Rebinning
- [ ] #119 PyPI metadata

# Minor issues
- [ ] #117 EnergyCal fix
- [ ] #115 clean up tool imports
- [ ] #113 negative inputs to Spectrum
- [ ] #112 Spectrum operations
- [ ] #107 various changes from quickstart notebook
- [ ] #101 Spectrum.bin_edges_kev property
- [ ] #94 Overview/quickstart notebook
- [ ] #56 Energycal notebook

**Comment by jccurtis** [comment]
Thanks for putting this together @markbandstra! I think it would be good for us to follow the semantic versioning standard: https://semver.org/. We should be releasing patch versions for every minor PR and subversions for the major ones. Thoughts?

**Comment by markbandstra** [comment]
@jccurtis that makes sense, if you map my "major" to "minor" and my "minor" to "patch". I think that moving to semantic versioning has #119 as a prerequisite since it would require straightening out our metadata, including version numbers.

**Comment by jccurtis** [comment]
@markbandstra I made a milestone and added all the above issues. I'm closing this checklist.

**Comment by markbandstra** [comment]
Oh clever, I didn't know you could do that. That is exactly what I was going for here.
